### ISSUE TITLE
Fix the "Play" option on the map

### ISSUE THREAD

**Issue by sarahcd** [movestore/MorningReport#6]
Currently the option to animate the map does not really work. Users would love to see this.

**Comment by annescharf** [comment]
@sarahcd , that is true because it takes time to plot the map. I'll check if there could be a way of making the animation work. Lets see...

**Comment by annescharf** [comment]
found a solution, but outcome is not beautiful as the map has to load every time 

https://github.com/movestore/MorningReport/commit/e801cba1cca832e5935da1b4e33fc6022ba29463
